version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
      time: "22:00"
      timezone: "America/Bogota"
    target-branch: "staging"

  - package-ecosystem: "npm"
    allow:
      - dependency-type: "production"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: monthly
      time: "22:00"
      timezone: "America/Bogota"
    target-branch: "staging"
