name: Development

on:
  pull_request:
    branches:
      - 'staging'
    types:
      - 'edited'
      - 'opened'
      - 'synchronize'

jobs:
  review_code:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16.x']

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
        env:
          CI: true

      - name: Linting
        run: yarn run eslint

      - name: Type checking
        run: yarn run tsc

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Bundlecheck
        uses: carlesnunez/check-my-bundlephobia@v1.8.0
        env:
          NODE_ENV: production
        with:
          ignore-dev-dependencies: true
          repo-token: ${{ github.token }}
